In [8]:
import numpy as np
import random
qubit_0 =  np.array([1,0]).reshape(2,)
qubit_1 =  np.array([0,1]).reshape(2,)
qubit_000 = np.kron(np.kron(qubit_0,qubit_0),qubit_0)
qubit_111 = np.kron(np.kron(qubit_1,qubit_1),qubit_1)
c = random.random()
c




0.8866583978076755

In [11]:
qubit_final=(qubit_000 + c* qubit_111) * np.sqrt((1/(1+c**2)))
qubit_final

array([0.74823745, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.66343102])

In [13]:
import numpy as np
CNOT_matrix=np.array([[1,0,0,0],
                      [0,1,0,0],
                      [0,0,0,1],
                      [0,0,1,0]])
CNOT_tensor=np.reshape(CNOT_matrix, (2,2,2,2))
H_matrix=(1/(np.sqrt(2)))*np.array([[1, 1],[1,-1]])
H_matrix

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

In [15]:

psi_1=np.zeros((2,2))
psi_2 = np.zeros((2,2))
psi_1[0,0] = psi_2[0,0] = 1
psi= np.kron(psi_1,psi_2)
psi=np.reshape(psi,(2,2,2,2))

psi=np.tensordot(CNOT_tensor,psi, ((2,3),(0,2))) 
psi=np.tensordot(CNOT_tensor,psi, ((2,3),(1,3)))

psi = np.tensordot(H_matrix,psi,(1,0))
psi = np.tensordot(H_matrix,psi,(1,1))

projectors=[np.array([[1,0],[0,0]]), np.array([[0,0],[0,1]])]
projected_2nd_qubit=np.tensordot(projectors[0],psi,(1,2))
projected_3rd_qubit=np.tensordot(projectors[0],psi,(1,3))



psi





array([[[[0.5, 0. ],
         [0. , 0. ]],

        [[0.5, 0. ],
         [0. , 0. ]]],


       [[[0.5, 0. ],
         [0. , 0. ]],

        [[0.5, 0. ],
         [0. , 0. ]]]])